global using System.Collections.Immutable;
global using System.Collections.ObjectModel;
global using System.ComponentModel;
global using CommunityToolkit.Mvvm.ComponentModel;
global using CommunityToolkit.Mvvm.Input;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Configuration;
global using Microsoft.UI.Xaml;
global using Microsoft.UI.Xaml.Controls;
global using Microsoft.UI.Xaml.Navigation;
global using MattEland.CodeReview.Core;
global using MattEland.CodeReview.Core.Analysis;
global using MattEland.CodeReview.Core.Configuration;
global using MattEland.CodeReview.Core.Git;
global using MattEland.CodeReview.Core.Models;
global using MattEland.CodeReview.Core.Profiles;
global using ApplicationExecutionState = Windows.ApplicationModel.Activation.ApplicationExecutionState;
